env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'problems/node8'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types:
    - off
settings:
  react:
    version: '16'
