export const Branches: string;
export const titleBlock: string;
export const title: string;
export const link: string;
export const color1: string;
export const color2: string;
export const color3: string;
export const color4: string;
export const color5: string;
